const brief={audience:'Engineers',objective:'Compute energy',inputs:'Power (kW), duration (h)',rules:'Energy = power × time',output:'Energy (kWh)',flow:'Enter → Validate → Compute',requirements:'No accounts or subscriptions',delivery:'web',storage:'none',auth:'none',integration:'none',hosting:'static',constraint:'auto',visual:'technical',accent:'#2563eb',siteLanguage:'ar-en',references:''};
const discovery={understanding:'أداة لحساب الطاقة من القدرة والوقت، مع وحدات واضحة.',project_name:'Energy planner',kind:'calculator',brief,questions:[]};
const technology={frontend:'HTML + CSS + JavaScript',backend:'No backend for transient calculations',server:false,rationale_ar:'الحساب محدد والمدخلات مؤقتة، لذلك تكفي واجهة بسيطة.',rationale_en:'A bounded transient calculation needs only a simple browser interface.',alternative_ar:'React إذا كبرت الحالة المشتركة.',alternative_en:'React if shared UI state becomes complex.',runtime_ar:'استضافة ملفات ثابتة.',runtime_en:'Static hosting.',zip_ar:'مصدر وملفات HTML وCSS وJS.',zip_en:'Source and deployable HTML, CSS and JavaScript.'};
const analysis={schema_version:1,kind:'calculator',summary:'A power-duration energy calculator',users:['Engineer'],capabilities:{storage:'none',auth:'none',integration:'none'},screens:[{name:'Energy workspace',purpose:'Compute energy',components:['Power input (kW)','Duration input (h)','Energy result (kWh)']}],flow:['Enter','Validate','Compute'],functional_requirements:['Compute approved power and duration values'],domain_rules:['Energy = power × time'],data_entities:[],design_notes:'Keep the inputs and result adjacent. Use a clear unit label and a legible numeric display; stack on mobile.',stack_suggestion:'HTML + CSS + JavaScript for transient calculations',acceptance_criteria:['Given 2kW and 3h, display 6kWh'],non_goals:['Accounts','Subscriptions'],assumptions:[],open_questions:['Rounding precision?'],risks:['Mixed units'],technology};
const blueprint={analysis,resolved_brief:brief,prd_markdown:'## Problem and outcome\n\nCompute energy from approved power and time inputs. The engineer enters a power value in kW and a duration in hours and receives kWh.\n\n## Functionality\n\nLabel input units, reject negative values and preserve valid data when an entry is invalid. Keep inputs next to the result on desktop and stack them on mobile. Do not add accounts or subscriptions.\n\n## Acceptance\n\nGiven 2 kW and 3 h, display 6 kWh. A negative duration must produce a field-specific validation error and no misleading result. Missing required values block computation.\n\n## Architecture and delivery\n\nUse HTML, CSS and modular JavaScript. Serve the finished browser assets on static HTTPS hosting. Provide source and setup instructions. Validate file path behavior before claiming direct local-file compatibility.'};
const project={name:'Energy planner',idea:'Calculator of energy from power and time',outputLanguage:'en'};
module.exports={brief,discovery,analysis,blueprint,project};

const shape={layout:'working',theme:'light',motion:'subtle',density:'comfortable',features:['compare'],customFeatures:'Compare approved scenarios'};
const sources=[{id:'R1',title:'Similar calculator',url:'https://example.com/calculator'},{id:'R2',title:'Official documentation',url:'https://example.org/docs'}];
const evidence={languages:['JavaScript'],similar_products:[{name:'Calculator A',source_id:'R1',similarity:'Power and time calculation',lesson:'Keep units close to results'},{name:'Calculator B',source_id:'R2',similarity:'Scenario comparison',lesson:'Display changed inputs'}],components:[{name:'Native HTML forms',version:'',source_id:'R2',purpose:'Accessible inputs'}]};
const researchResult={project_name:'Energy planner',analysis,resolved_brief:brief,shape,research:{searched_at:'2026-10-04T10:00:00Z',sources,...evidence}};
module.exports.shape=shape;module.exports.sources=sources;module.exports.evidence=evidence;module.exports.researchResult=researchResult;
