import {test} from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {createSupabaseHandler} from '../supabase/functions/_shared/handler.mjs';
const require=createRequire(import.meta.url),fixture=require('./fixtures.cjs'),B=require('../public/backend.js');
const origin='https://forge.example',publicKey='sb_publishable_test_public_123456',adminKey='sb_secret_test_server_123456';
const env={OPENAI_API_KEY:'fake-server-only-openai-key',OPENAI_MODEL:'model-test',SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEYS:JSON.stringify({default:adminKey}),SUPABASE_PUBLISHABLE_KEYS:JSON.stringify({default:publicKey}),FORGE_ALLOWED_ORIGINS:origin};
const request=(method='POST',extra={},body={project:fixture.project})=>new Request('https://example.supabase.co/functions/v1/ai-assist'+(method==='GET'?'?action=status':''),{method,headers:{origin,apikey:publicKey,'Content-Type':'application/json',...extra},body:['GET','OPTIONS','HEAD'].includes(method)?undefined:JSON.stringify(body)});
const reply=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
test('Supabase preflight and health allow only the configured origin and public key',async()=>{const handler=createSupabaseHandler(env);const pre=await handler(request('OPTIONS'));assert.equal(pre.status,204);assert.equal(pre.headers.get('Access-Control-Allow-Origin'),origin);assert.match(pre.headers.get('Access-Control-Allow-Headers'),/apikey/);const status=await handler(request('GET'));assert.equal(status.status,200);assert.equal((await status.json()).configuration_only,true);assert.equal((await handler(request('GET',{origin:'https://other.example'}))).status,403);assert.equal((await handler(request('GET',{apikey:adminKey}))).status,401);});
test('Missing Secrets or invalid input never starts paid inference',async()=>{let calls=0;const handler=createSupabaseHandler({...env,OPENAI_API_KEY:''},{researchProject:async()=>{calls++;}});const r=await handler(request());assert.equal(r.status,503);assert.ok(!(await r.text()).includes(env.OPENAI_API_KEY));const good=createSupabaseHandler(env,{researchProject:async()=>{calls++;}});assert.equal((await good(request('POST',{},{}))).status,400);assert.equal(calls,0);});
test('Durable quota is checked with a server secret before returning researched fields',async()=>{let researchCalls=0,quotaBody;const handler=createSupabaseHandler(env,{fetch:async(url,o)=>{assert.equal(url,env.SUPABASE_URL+'/rest/v1/rpc/consume_forge_research_quota');assert.equal(o.headers.apikey,adminKey);assert.equal(o.headers.Authorization,undefined);quotaBody=JSON.parse(o.body);assert.match(quotaBody.p_client_hash,/^[a-f0-9]{64}$/);assert.equal(quotaBody.p_global_limit,20);return reply(true);},researchProject:async(p,e)=>{researchCalls++;assert.deepEqual(p,fixture.project);assert.equal(e.OPENAI_API_KEY,env.OPENAI_API_KEY);return fixture.researchResult;}});const r=await handler(request());assert.equal(r.status,200);assert.equal(researchCalls,1);const text=await r.text();assert.ok(!text.includes(adminKey));assert.ok(!text.includes(env.OPENAI_API_KEY));assert.equal(JSON.parse(text).research.sources.length,2);});
test('SQL setup errors and exhausted quotas fail closed before inference',async()=>{for(const [response,code]of [[reply({error:'private server diagnostic'},403),503],[reply(false),429]]){let calls=0;const handler=createSupabaseHandler(env,{fetch:async()=>response,researchProject:async()=>{calls++;}});const r=await handler(request());assert.equal(r.status,code);assert.equal(calls,0);assert.ok(!(await r.text()).includes('private server diagnostic'));}});
test('Legacy anon keys work, but service_role JWTs and OpenAI keys are rejected by frontend',()=>{const jwt=role=>'eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify({role})).toString('base64url')+'.sig';assert.equal(B.isPublicKey(jwt('anon')),true);assert.equal(B.isPublicKey(jwt('service_role')),false);assert.equal(B.isPublicKey('sk-proj-not-for-browser'),false);assert.throws(()=>B.set({provider:'supabase',url:'https://example.supabase.co',key:adminKey}));assert.throws(()=>B.set({provider:'supabase',url:'https://attacker.example',key:publicKey}));assert.throws(()=>B.set({provider:'supabase',url:'https://example.supabase.co/functions/v1',key:publicKey}));B.clear();});
test('Frontend sends a public key only to the Supabase function and can restore the original backend',async()=>{const old=globalThis.fetch;const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,o});return reply({ready:true,research:true});};try{B.set({provider:'supabase',url:'https://example.supabase.co/',key:publicKey});await B.request('/api/status',{headers:{Accept:'application/json'}});await B.request('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:fixture.project})});assert.equal(calls[0].url,'https://example.supabase.co/functions/v1/ai-assist?action=status');assert.equal(calls[1].o.headers.apikey,publicKey);assert.equal(calls[1].o.headers.Authorization,undefined);B.clear();await B.request('/api/status');assert.equal(calls[2].url,'/api/status');}finally{B.clear();globalThis.fetch=old;}});
test('Supabase route integrates actual research stages after the quota succeeds',async()=>{const old=globalThis.fetch;let step=0;globalThis.fetch=async(url,o)=>{step++;if(step===1){assert.match(url,/rest\/v1\/rpc/);return reply(true);}const body=JSON.parse(o.body);assert.equal(o.headers.Authorization,'Bearer '+env.OPENAI_API_KEY);if(step===2){assert.equal(body.tool_choice,'required');return reply({status:'completed',output:[{type:'web_search_call',status:'completed',action:{sources:fixture.sources}},{type:'message',content:[{type:'output_text',text:'Two related researched products and relevant components.'}]}]});}assert.equal(body.text.format.strict,true);return reply({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({project_name:fixture.project.name,analysis:fixture.analysis,resolved_brief:fixture.brief,shape:fixture.shape,evidence:fixture.evidence})}]}]});};try{const handler=createSupabaseHandler(env);const r=await handler(request());assert.equal(r.status,200);assert.equal(step,3);assert.equal((await r.json()).analysis.kind,'calculator');}finally{globalThis.fetch=old;}});

test('Configuration status names missing settings without revealing stored secrets',async()=>{
const handler=createSupabaseHandler({...env,OPENAI_MODEL:''});const r=await handler(request('GET'));assert.equal(r.status,200);const data=await r.json();assert.equal(data.ready,false);assert.deepEqual(data.missing_configuration,['OPENAI_MODEL']);assert.match(data.error,/OPENAI_MODEL/);assert.ok(!JSON.stringify(data).includes(env.OPENAI_API_KEY));assert.ok(!JSON.stringify(data).includes(adminKey));
});

test('A complete function URL keeps the deployed slug across saved settings',async()=>{
const old=globalThis.fetch,calls=[];globalThis.fetch=async(url,o)=>{calls.push(url);return reply({ready:true,research:true});};try{
const c=B.set({provider:'supabase',url:'https://example.supabase.co/functions/v1/custom-research',key:publicKey});assert.equal(c.functionName,'custom-research');assert.equal(B.validateConfig(c).functionName,'custom-research');await B.request('/api/status');await B.request('/api/research',{method:'POST'});assert.deepEqual(calls,['https://example.supabase.co/functions/v1/custom-research?action=status','https://example.supabase.co/functions/v1/custom-research']);
assert.throws(()=>B.set({provider:'supabase',url:'https://example.supabase.co/functions/v1/custom?redirect=bad',key:publicKey}));assert.throws(()=>B.set({provider:'supabase',url:'https://example.supabase.co',key:publicKey,functionName:'../private'}));
const migrated=B.validateConfig({provider:'supabase',url:'https://ofmvqfjsxvqscargxpim.supabase.co',key:publicKey});assert.equal(migrated.functionName,'super-handler');
}finally{B.clear();globalThis.fetch=old;}
});
