// Action-level DOM harness; this does not verify browser layout or rendering.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const dir=path.join(__dirname,'../public');

function harness(options={}){
const elements=[],ids=new Map(),tools=new Map(),clipboard=[],downloads=[],calls=[];
const decode=s=>s.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,'&');
class Element{
constructor(tag,attrs={}){this.tag=tag;this.attrs=attrs;this.dataset={};for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.id=attrs.id;this.value=attrs.value||'';this.disabled=Object.hasOwn(attrs,'disabled');this.listeners={};this.textContent='';this._html='';const cls=new Set((attrs.class||'').split(' ').filter(Boolean));this.classList={add:s=>cls.add(s),remove:s=>cls.delete(s),contains:s=>cls.has(s),toggle:(s,v)=>{v=v===undefined?!cls.has(s):v;v?cls.add(s):cls.delete(s);}};this.style={setProperty(){}};this.lastElementChild={appendChild(){}};elements.push(this);if(this.id)ids.set(this.id,this);}
set innerHTML(s){this._html=s;if(['pageEditor','featureEditor'].includes(this.id)){for(const m of s.matchAll(/<(input|button)([^>]*)>/g))new Element(m[1],attrs(m[2]));for(const m of s.matchAll(/<textarea([^>]*)>([\s\S]*?)<\/textarea>/g)){const e=new Element('textarea',attrs(m[1]));e.value=decode(m[2]);}}}
get innerHTML(){return this._html;}
setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}addEventListener(k,f){(this.listeners[k]??=[]).push(f);}async fire(k,x={}){for(const f of this.listeners[k]||[])await f({preventDefault(){},...x});}closest(selector){return selector==='[data-page-action]'&&this.dataset.pageAction?this:null;}remove(){}focus(){this.focused=true;}select(){this.selected=true;}reportValidity(){return !!this.value;}appendChild(){}reset(){}click(){if(this.tag==='a')downloads.push({name:this.download,href:this.href});return this.fire('click');}}
function attrs(s){const a={};for(const m of s.matchAll(/([\w-]+)(?:="([^"]*)")?/g))a[m[1]]=decode(m[2]||'');return a;}
const html=fs.readFileSync(path.join(dir,'index.html'),'utf8');for(const m of html.matchAll(/<(button|input|select|textarea|details|div|section|form|h1|span|nav|p|strong)([^>]*)>/g))new Element(m[1],attrs(m[2]));
for(const m of html.matchAll(/<select([^>]*)>([\s\S]*?)<\/select>/g)){const a=attrs(m[1]);ids.get(a.id).value=m[2].match(/<option value="([^"]*)"/)?.[1]||'';}
const query=s=>{const d=s.match(/\[data-([\w-]+)(?:="([^"]+)")?\]/);if(d)return elements.filter(e=>e.dataset[d[1]]!==undefined&&(d[2]===undefined||e.dataset[d[1]]===d[2]));if(s.startsWith('.'))return elements.filter(e=>e.classList.contains(s.slice(1)));return[];};
const document={getElementById:id=>ids.get(id),querySelectorAll:query,querySelector:s=>query(s)[0],body:{appendChild(){}},createElement:t=>new Element(t),modelContext:{registerTool(t){assert.ok(t.inputSchema);tools.set(t.name,t);}}};
const context={document,location:{origin:'https://forge.example'},navigator:{clipboard:{writeText:async t=>clipboard.push(t)}},Blob,URL:Object.assign(class extends URL {},{createObjectURL:()=> 'blob:test',revokeObjectURL(){}}),atob,setTimeout:()=>1,clearTimeout(){},AbortController,console,fetch:async(url,o)=>{calls.push({url,options:o});return options.fetch?options.fetch(url,o):{ok:true,json:async()=>({ready:false,research:false})};}};context.window=context;context.scrollTo=()=>{};context.addEventListener=()=>{};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(dir,'engine.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(dir,'studio.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(dir,'backend.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(dir,'app.js'),'utf8'),context);
return{ids,tools,query,clipboard,downloads,calls,get:id=>{assert.ok(ids.has(id),'Missing DOM id '+id);return ids.get(id);}};
}

const fixture=require('./fixtures.cjs');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('Offline Auto announces missing connection and never substitutes local inference',async()=>{const h=harness();await tick();h.get('projectIdea').value='موقع شركة مقاولات';await h.get('ideaForm').fire('submit');assert.equal(h.get('shapeView').classList.contains('hidden'),true);assert.match(h.get('ideaError').textContent,/غير مفعّل/);assert.equal(h.calls.filter(x=>x.url==='/api/research').length,0);assert.ok(!h.ids.has('importJSON'));});
test('Manual pages, capabilities and theme reach the unified document',async()=>{const h=harness();h.get('projectIdea').value='نظام داخلي';await h.get('customStart').fire('click');h.get('theme').value='dark';await h.get('theme').fire('input');h.get('pageName0').value='مكتب الموافقة';await h.get('pageEditor').fire('input',{target:h.get('pageName0')});h.get('pageComponents0').value='قبول أو رفض مع السبب';await h.get('pageEditor').fire('input',{target:h.get('pageComponents0')});await h.get('featureEditor').fire('change',{target:{dataset:{feature:'history'},checked:true}});await h.get('addPage').fire('click');await h.get('generate').fire('click');const doc=h.get('prdOutput').value;for(const text of ['مكتب الموافقة','قبول أو رفض مع السبب','الخلفية: داكن','سجل الإجراءات','صفحة جديدة'])assert.ok(doc.includes(text));assert.equal((doc.match(/^## /gm)||[]).length,(doc.match(/^### برومبت تنفيذ هذا القسم$/gm)||[]).length);assert.ok(!h.ids.has('buildOutput'));await h.get('backShape').fire('click');assert.equal(h.get('theme').value,'dark');});
test('Copy and export use the edited single document',async()=>{const h=harness();h.get('projectIdea').value='حاسبة الطاقة';await h.get('customStart').fire('click');await h.get('generate').fire('click');h.get('prdOutput').value+='\nApproved formula: result = 42';await h.get('copyPrd').fire('click');assert.equal(h.clipboard[0],h.get('prdOutput').value);await h.get('downloadPrd').fire('click');assert.equal(h.downloads[0].name,'project-prd.md');});
test('Empty descriptions are blocked and unsafe text is escaped in preview',async()=>{const h=harness();await h.get('ideaForm').fire('submit');assert.equal(h.get('ideaError').classList.contains('hidden'),false);h.get('projectIdea').value='A custom tool';h.get('projectName').value='<img src=x onerror=alert(1)>';await h.get('customStart').fire('click');assert.ok(h.get('mockPreview').innerHTML.includes('&lt;img'));assert.ok(!h.get('mockPreview').innerHTML.includes('<img'));});
test('Connected Auto fills AI fields and displays source links without asking for JSON',async()=>{const h=harness({fetch:async url=>({ok:true,json:async()=>url==='/api/status'?{ready:true,research:true}:fixture.researchResult})});await tick();h.get('projectIdea').value=fixture.project.idea;h.get('projectName').value=fixture.project.name;h.get('outputLanguage').value='en';await h.get('ideaForm').fire('submit');assert.equal(h.get('audience').value,'Engineers');assert.equal(h.get('inputs').value,fixture.brief.inputs);assert.equal(h.get('output').value,fixture.brief.output);assert.equal(h.get('pageName0').value,'Energy workspace');assert.ok(h.get('researchResults').innerHTML.includes('https://example.com/calculator'));await h.get('generate').fire('click');assert.match(h.get('prdOutput').value,/6kWh/);assert.equal((h.get('prdOutput').value.match(/^## /gm)||[]).length,(h.get('prdOutput').value.match(/^### Implementation prompt$/gm)||[]).length);});
test('Failed Auto preserves manual edits and clears the busy overlay',async()=>{const h=harness({fetch:async url=>url==='/api/status'?{ok:true,json:async()=>({ready:true,research:true})}:{ok:false,json:async()=>({error:'Search failed'})}});await tick();h.get('projectIdea').value='حاسبة';await h.get('customStart').fire('click');h.get('rules').value='Use only the approved rule';h.get('accent').value='#ff0000';await h.get('accent').fire('input');await h.get('autoAll').fire('click');assert.equal(h.get('rules').value,'Use only the approved rule');assert.equal(h.get('accent').value,'#ff0000');assert.equal(h.get('researchBusy').classList.contains('hidden'),true);await h.get('generate').fire('click');assert.match(h.get('prdOutput').value,/Use only the approved rule/);});
test('Canceling Auto keeps prior fields and never commits late results',async()=>{let resolve;const h=harness({fetch:async url=>url==='/api/status'?{ok:true,json:async()=>({ready:true,research:true})}:new Promise(r=>{resolve=r;})});await tick();h.get('projectIdea').value='حاسبة';await h.get('customStart').fire('click');h.get('rules').value='Keep this rule';await h.get('rules').fire('input');const pending=h.get('autoAll').fire('click');await h.get('cancelResearch').fire('click');resolve({ok:true,json:async()=>fixture.researchResult});await pending;assert.equal(h.get('rules').value,'Keep this rule');assert.equal(h.get('researchBusy').classList.contains('hidden'),true);});
test('Backend settings use Supabase for status and Auto, then preserve source links in PRD',async()=>{const requests=[];const h=harness({fetch:async(url,o)=>{requests.push({url,o});return {ok:true,json:async()=>url.includes('/ai-assist')?(o?.method==='POST'?fixture.researchResult:{ready:true,research:true}):{ready:false,research:false}};}});await tick();h.get('backendProvider').value='supabase';await h.get('backendProvider').fire('change');h.get('supabaseUrl').value='https://example.supabase.co';h.get('supabasePublicKey').value='sb_publishable_test_public_123456';await h.get('saveBackend').fire('click');assert.match(h.get('connectionStatus').textContent,/مهيأة/);h.get('projectIdea').value=fixture.project.idea;await h.get('ideaForm').fire('submit');const auto=requests.find(v=>v.o?.method==='POST');assert.equal(auto.url,'https://example.supabase.co/functions/v1/ai-assist');assert.equal(auto.o.headers.apikey,'sb_publishable_test_public_123456');await h.get('generate').fire('click');assert.match(h.get('prdOutput').value,/https:\/\/example.com\/calculator/);});
test('An OpenAI key in frontend settings is rejected without sending it or changing the backend',async()=>{const h=harness();await tick();h.get('backendProvider').value='supabase';h.get('supabaseUrl').value='https://example.supabase.co';h.get('supabasePublicKey').value='sk-proj-never-send-this';await h.get('saveBackend').fire('click');assert.match(h.get('backendError').textContent,/المفتاح العام/);assert.equal(h.calls.length,1);assert.ok(!JSON.stringify(h.calls).includes('sk-proj-never-send-this'));});

test('Auto rechecks configuration and recovers after server Secrets are completed',async()=>{
let configured=false;const h=harness({fetch:async(url,o)=>({ok:true,status:200,json:async()=>o?.method==='POST'?fixture.researchResult:{ready:configured,research:configured,error:configured?undefined:'Missing OPENAI_MODEL'}})});
await tick();h.get('backendProvider').value='supabase';h.get('supabaseUrl').value='https://example.supabase.co';h.get('supabasePublicKey').value='sb_publishable_test_public_123456';await h.get('saveBackend').fire('click');
h.get('projectIdea').value=fixture.project.idea;await h.get('ideaForm').fire('submit');assert.match(h.get('ideaError').textContent,/OPENAI_MODEL/);assert.equal(h.get('backendSettings').open,true);assert.equal(h.calls.filter(x=>x.options?.method==='POST').length,0);
configured=true;await h.get('ideaForm').fire('submit');assert.equal(h.calls.filter(x=>x.options?.method==='POST').length,1);assert.equal(h.get('backendError').classList.contains('hidden'),true);assert.equal(h.get('audience').value,'Engineers');
});
test('Supabase gateway and blocked-origin failures show actionable connection guidance',async()=>{
for(const [status,message]of [[401,/Verify JWT/],[404,/ai-assist/],[0,/https:\/\/forge.example/]]){
const h=harness({fetch:async url=>{if(!url.includes('supabase.co'))return {ok:false,status:404,json:async()=>{throw Error('HTML');}};if(!status)throw TypeError('Failed to fetch');return {ok:false,status,json:async()=>({message:'Gateway error'})};}});await tick();h.get('backendProvider').value='supabase';h.get('supabaseUrl').value='https://example.supabase.co';h.get('supabasePublicKey').value='sb_publishable_test_public_123456';await h.get('saveBackend').fire('click');assert.match(h.get('backendError').textContent,message);assert.equal(h.get('autoStart').disabled,false);
}
});

test('Full deployed function URL routes status and Auto to super-handler',async()=>{
const h=harness({fetch:async(url,o)=>({ok:true,status:200,json:async()=>url.includes('/super-handler')?(o?.method==='POST'?fixture.researchResult:{ready:true,research:true}):{ready:false,research:false}})});await tick();h.get('backendProvider').value='supabase';h.get('supabaseUrl').value='https://ofmvqfjsxvqscargxpim.supabase.co/functions/v1/super-handler';h.get('supabasePublicKey').value='sb_publishable_test_public_123456';await h.get('saveBackend').fire('click');assert.match(h.get('connectionStatus').textContent,/مهيأة/);assert.match(h.get('supabaseUrl').value,/super-handler$/);h.get('projectIdea').value=fixture.project.idea;await h.get('ideaForm').fire('submit');assert.equal(h.calls.find(x=>x.options?.method==='POST').url,'https://ofmvqfjsxvqscargxpim.supabase.co/functions/v1/super-handler');assert.equal(h.get('audience').value,'Engineers');
});
