// Action-level DOM harness; this does not verify browser layout or rendering.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const dir=path.join(__dirname,'../public');

function harness(options={}){
const elements=[],ids=new Map(),tools=new Map(),clipboard=[],downloads=[],calls=[];
const decode=s=>s.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,'&');
class Element{
constructor(tag,attrs={}){this.tag=tag;this.attrs=attrs;this.dataset={};for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.id=attrs.id;this.value=attrs.value||'';this.disabled=Object.hasOwn(attrs,'disabled');this.listeners={};this.textContent='';this._html='';const cls=new Set((attrs.class||'').split(' ').filter(Boolean));this.classList={add:s=>cls.add(s),remove:s=>cls.delete(s),contains:s=>cls.has(s),toggle:(s,v)=>{v=v===undefined?!cls.has(s):v;v?cls.add(s):cls.delete(s);}};this.style={setProperty(){}};this.lastElementChild={appendChild(){}};elements.push(this);if(this.id)ids.set(this.id,this);}
set innerHTML(s){this._html=s;if(['pageEditor','featureEditor'].includes(this.id)){for(const m of s.matchAll(/<(input|button)([^>]*)>/g))new Element(m[1],attrs(m[2]));for(const m of s.matchAll(/<textarea([^>]*)>([\s\S]*?)<\/textarea>/g)){const e=new Element('textarea',attrs(m[1]));e.value=decode(m[2]);}}}
get innerHTML(){return this._html;}
setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}addEventListener(k,f){(this.listeners[k]??=[]).push(f);}async fire(k,x={}){for(const f of this.listeners[k]||[])await f({preventDefault(){},...x});}closest(selector){return selector==='[data-page-action]'&&this.dataset.pageAction?this:null;}remove(){}focus(){this.focused=true;}select(){this.selected=true;}reportValidity(){return !!this.value;}appendChild(){}reset(){}click(){if(this.tag==='a')downloads.push({name:this.download,href:this.href});return this.fire('click');}}
function attrs(s){const a={};for(const m of s.matchAll(/([\w-]+)(?:="([^"]*)")?/g))a[m[1]]=decode(m[2]||'');return a;}
const html=fs.readFileSync(path.join(dir,'index.html'),'utf8');for(const m of html.matchAll(/<(button|input|select|textarea|div|section|form|h1|span|nav|p|strong)([^>]*)>/g))new Element(m[1],attrs(m[2]));
for(const m of html.matchAll(/<select([^>]*)>([\s\S]*?)<\/select>/g)){const a=attrs(m[1]);ids.get(a.id).value=m[2].match(/<option value="([^"]*)"/)?.[1]||'';}
const query=s=>{const d=s.match(/\[data-([\w-]+)(?:="([^"]+)")?\]/);if(d)return elements.filter(e=>e.dataset[d[1]]!==undefined&&(d[2]===undefined||e.dataset[d[1]]===d[2]));if(s.startsWith('.'))return elements.filter(e=>e.classList.contains(s.slice(1)));return[];};
const document={getElementById:id=>ids.get(id),querySelectorAll:query,querySelector:s=>query(s)[0],body:{appendChild(){}},createElement:t=>new Element(t),modelContext:{registerTool(t){assert.ok(t.inputSchema);tools.set(t.name,t);}}};
const context={document,navigator:{clipboard:{writeText:async t=>clipboard.push(t)}},Blob,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},setTimeout:()=>1,clearTimeout(){},AbortController,console,fetch:async()=>{throw Error('Studio must not call an API');}};context.window=context;context.scrollTo=()=>{};context.addEventListener=()=>{};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(dir,'engine.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(dir,'studio.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(dir,'app.js'),'utf8'),context);
return{ids,tools,query,clipboard,downloads,calls,get:id=>{assert.ok(ids.has(id),'Missing DOM id '+id);return ids.get(id);}};
}

test('Auto shows editable configuration and produces a full prompt without an API or JSON',async()=>{const h=harness();h.get('projectIdea').value='موقع شركة مقاولات';await h.get('ideaForm').fire('submit');assert.equal(h.get('shapeView').classList.contains('hidden'),false);assert.equal(h.get('kind').value,'company');assert.ok(h.ids.has('pageName0'));await h.get('generate').fire('click');assert.equal(h.get('outputView').classList.contains('hidden'),false);assert.match(h.get('buildOutput').value,/موقع شركة مقاولات/);assert.ok(!h.ids.has('importJSON'));});
test('Manual page edits, additional features and theme reach the generated prompt',async()=>{const h=harness();h.get('projectIdea').value='نظام داخلي';await h.get('customStart').fire('click');h.get('theme').value='dark';await h.get('theme').fire('input');h.get('pageName0').value='مكتب الموافقة';await h.get('pageEditor').fire('input',{target:h.get('pageName0')});h.get('pageComponents0').value='قبول أو رفض مع السبب';await h.get('pageEditor').fire('input',{target:h.get('pageComponents0')});await h.get('featureEditor').fire('change',{target:{dataset:{feature:'history'},checked:true}});await h.get('addPage').fire('click');await h.get('generate').fire('click');assert.match(h.get('buildOutput').value,/مكتب الموافقة/);assert.match(h.get('buildOutput').value,/قبول أو رفض مع السبب/);assert.match(h.get('buildOutput').value,/الخلفية: داكن/);assert.match(h.get('buildOutput').value,/سجل الإجراءات/);assert.match(h.get('buildOutput').value,/صفحة جديدة/);await h.get('backShape').fire('click');assert.equal(h.get('theme').value,'dark');});
test('PRD edits update the prompt; copy and download deliver the displayed output',async()=>{const h=harness();h.get('projectIdea').value='حاسبة الطاقة';await h.get('ideaForm').fire('submit');await h.get('generate').fire('click');h.get('prdOutput').value+='\nApproved formula: result = 42';await h.get('refreshPrompt').fire('click');assert.ok(h.get('buildOutput').value.endsWith('Approved formula: result = 42'));await h.get('copyBuild').fire('click');assert.equal(h.clipboard[0],h.get('buildOutput').value);await h.get('downloadBuild').fire('click');assert.equal(h.downloads[0].name,'project-build-prompt.txt');});
test('Empty idea cannot generate and unsafe strings remain escaped in live preview',async()=>{const h=harness();await h.get('ideaForm').fire('submit');assert.equal(h.get('ideaError').classList.contains('hidden'),false);assert.equal(h.get('shapeView').classList.contains('hidden'),true);h.get('projectIdea').value='A custom tool';h.get('projectName').value='<img src=x onerror=alert(1)>';await h.get('ideaForm').fire('submit');assert.ok(h.get('mockPreview').innerHTML.includes('&lt;img'));assert.ok(!h.get('mockPreview').innerHTML.includes('<img'));});
test('Auto refresh preserves explicit domain rules while replacing shaping choices',async()=>{const h=harness();h.get('projectIdea').value='حاسبة';await h.get('ideaForm').fire('submit');h.get('rules').value='Use only the approved rule';h.get('accent').value='#ff0000';await h.get('accent').fire('input');await h.get('autoAll').fire('click');assert.equal(h.get('rules').value,'Use only the approved rule');assert.equal(h.get('accent').value,'#2563eb');await h.get('generate').fire('click');assert.match(h.get('buildOutput').value,/Use only the approved rule/);});
