import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import fixture from './fixtures.cjs';
const source=await readFile(new URL('../dist/server/index.js',import.meta.url),'utf8');const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const env={OPENAI_API_KEY:'sk-fake-key-for-unit-tests',OPENAI_MODEL:'model-unit-test'};
function req(path,body,extra={}){return new Request('https://forge.example'+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://forge.example',...extra},body:JSON.stringify(body)});}
function upstream(data,status='completed'){return new Response(JSON.stringify({status,output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(data)}]}]}),{headers:{'Content-Type':'application/json'}});}
test('The app serves normal screens without JSON or import fields',async()=>{const r=await worker.fetch(new Request('https://forge.example/'),{});assert.equal(r.status,200);const html=await r.text();assert.ok(!html.includes('JSON'));assert.ok(!html.includes('importJSON'));assert.match(html,/افهم فكرتي/);assert.match(html,/نسخة 2.0/);});
test('Unconfigured AI returns an honest status and actionable failure',async()=>{const r=await worker.fetch(new Request('https://forge.example/api/status'),{});assert.deepEqual(await r.json(),{ready:false});const no=await worker.fetch(req('/api/discover',{project:fixture.project}),{});assert.equal(no.status,503);assert.match((await no.json()).error,/تفعيل اتصال/);});
test('API secret stays server-side and a structured discovery response is validated',async()=>{const old=globalThis.fetch;let requestBody;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.headers.Authorization,'Bearer '+env.OPENAI_API_KEY);requestBody=JSON.parse(options.body);return upstream(fixture.discovery);};try{const r=await worker.fetch(req('/api/discover',{project:fixture.project}),env);assert.equal(r.status,200);const text=await r.text();assert.ok(!text.includes(env.OPENAI_API_KEY));assert.equal(requestBody.store,false);assert.equal(requestBody.text.format.strict,true);assert.equal(requestBody.text.format.type,'json_schema');assert.equal(JSON.parse(text).questions.length,0);}finally{globalThis.fetch=old;}});
test('User answers are matched to server-validated questions and incorporated in generation',async()=>{const old=globalThis.fetch;const discovery={...fixture.discovery,questions:[{id:'q1',question:'ما وحدة القدرة؟',options:['kW','W']}]};let prompt;globalThis.fetch=async(_,o)=>{prompt=JSON.parse(o.body).input;return upstream(fixture.blueprint);};try{const r=await worker.fetch(req('/api/blueprint',{project:fixture.project,discovery,answers:[{id:'q1',question:'malicious replacement',answer:'kW'}]}),env);assert.equal(r.status,200);assert.ok(prompt.includes('ما وحدة القدرة؟'));assert.ok(!prompt.includes('malicious replacement'));assert.match((await r.json()).prd_markdown,/Given 2 kW and 3 h/);}finally{globalThis.fetch=old;}});
test('Invalid input, missing answers, cross-site and unsupported methods are rejected before inference',async()=>{for(const [request,expected]of [[req('/api/discover',{project:{idea:'',outputLanguage:'en'}}),400],[req('/api/discover',{project:fixture.project},{Origin:'https://other.example'}),403],[new Request('https://forge.example/api/discover'),405],[req('/api/blueprint',{project:fixture.project,discovery:{...fixture.discovery,questions:[{id:'q1',question:'Purpose?',options:[]}]},answers:[]}),400]])assert.equal((await worker.fetch(request,env)).status,expected);});
test('Malformed, incomplete and refused upstream results never become success',async()=>{const old=globalThis.fetch;try{for(const response of [upstream({},'completed'),upstream(fixture.discovery,'incomplete'),new Response(JSON.stringify({status:'completed',output:[{content:[{type:'refusal',refusal:'No'}]}]}))]){globalThis.fetch=async()=>response;const r=await worker.fetch(req('/api/discover',{project:fixture.project}),env);assert.ok(r.status>=400);assert.ok((await r.json()).error);}}finally{globalThis.fetch=old;}});
test('Unexpected upstream failures do not expose provider details or keys',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response('sk-provider-secret diagnostic details',{status:401});try{const r=await worker.fetch(req('/api/discover',{project:fixture.project}),env);assert.equal(r.status,503);assert.ok(!(await r.text()).includes('sk-provider-secret'));}finally{globalThis.fetch=old;}});
